add_newline = true
command_timeout = 4000

[character]
success_symbol = "[â¯](bold yellow)"

[directory]
style = "bold blue"

[git_branch]
style = "bold yellow"




[python]
symbol = "ğŸ "
version_format = "v${major}.${minor}"

[java]
version_format = "v${major}.${minor}"
symbol = "î‰– "

[scala]
version_format = "v${major}.${minor}"
symbol = "îœ· "

[terraform]
symbol = "ï„µ "
style = "bold purple"

[golang]
version_format = "v${major}.${minor}"
symbol = "îœ¤ "

[rust]
version_format = "v${major}.${minor}"
symbol = "î¨ "

# Disabled
[gcloud]
disabled = true

[aws]
disabled = true

[helm]
disabled = true

[kubernetes]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true
